name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir servidor local
        run: |
          python3 -m http.server 8080 &
          sleep 10

      - name: Rodar ZAP (SEM docker manual)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://127.0.0.1:8080"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-r zap_report.html -w zap_report.md -J zap_report.json"

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: |
            zap_report.html
            zap_report.md
            zap_report.json
