name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Iniciar aplicação local
        run: |
          python3 -m http.server 8080 &
          sleep 10

      - name: Criar pasta do relatório
        run: |
          mkdir -p zap-report
          chmod 777 zap-report

      - name: Rodar OWASP ZAP e gerar relatório HTML
        run: |
          docker run --rm \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}/zap-report:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://host.docker.internal:8080 \
            -r zap_report.html \
            -w zap_report.md \
            -J zap_report.json \
            || true

      - name: Verificar relatórios gerados
        if: always()
        run: |
          echo "Conteúdo da pasta zap-report:"
          ls -la zap-report

      - name: Salvar relatório como Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: zap-report/

      # (FALHA DO PIPELINE)
      - name: Falhar pipeline se houver vulnerabilidades
        run: |
          echo "Verificando alertas no relatório..."
          if grep -E "Medium|High|Critical" zap-report/zap_report.html; then
            echo "Vulnerabilidades encontradas! Falhando pipeline..."
            exit 1
          else
            echo "Nenhuma vulnerabilidade crítica encontrada."
          fi
